# Generated by Django 5.0.2 on 2024-04-25 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('aadhaar', models.BigIntegerField(unique=True)),
                ('qualification', models.CharField(choices=[('SSC', 'SSC'), ('Intermediate', 'Intermediate'), ('U.G', 'U.G'), ('P.G', 'P.G'), ('Ph.D', 'Ph.D'), ('None', 'None')], max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=20)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('INDIA', 'INDIA'), ('INDIA', 'INDIA')], max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=20)),
                ('postalcode', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_signup',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
